import type { Phase1SurveyFormData } from '../types/phase1.types';

export const getDefaultInitialFormData = (parcelId: string = ''): Phase1SurveyFormData => ({
  parcelId,
  projectParcelCode: '',
  officialCadastralCode: '',
  buildingName: '',
  houseNumber: '',
  street: '',
  ownerName: '',
  ownerPhone: '',
  objectGroup: 'GENERAL',
  chainage: 'Km 0+000',
  metroOffsetDistance: '15.0m',
  clearanceOffsetDistance: '5.2m',
  gpsCoords: { lat: 10.7769, lng: 106.7009 },
  adjacentBuildings: {
    left: { type: '', details: '', note: '' },
    right: { type: '', details: '', note: '' },
    back: { type: '', details: '', note: '' },
  },
  surveyCaseType: 'NORMAL',
  isAbsenteeSurvey: false,
  absenteeReason: '',
  absenteeMinutesPhotos: [],
  underConstructionPhotos: [],
  constructionStageNotes: '',
  isVacantLand: false,
  vacantLandStatus: '',
  vacantLandNotes: '',
  vacantLandPhotos: [],

  photoP01: { url: '', notApplicable: false },
  photoP02: {
    url: '',
    notApplicable: false,
    polygonPoints: [],
    floorSplits: [],
    widthM: '',
    heightM: '',
  },
  photoP03: { url: '', notApplicable: false, tag: 'Bên hông trái', additionalPhotos: [] },
  photoP04: { url: '', notApplicable: false },

  usageFunction: '',
  aboveFloors: 0,
  undergroundFloors: 0,
  constructionAreaM2: '',
  buildingHeightM: '',
  constructionYear: 2026,
  isEstimatedYear: false,
  structureSystem: '',
  foundationType: '',
  foundationSource: 'Bản vẽ hoàn công',
  pileDimensionMm: '',
  pileWidthMm: '',
  pileLengthMm: '',
  foundationDepthM: '',
  foundationDensity: '',
  foundationSpacingM: '',
  foundationNotes: '',
  asBuiltDrawingPhotoUrl: '',
  asBuiltDrawingPhotos: [],
  asBuiltDrawingFiles: [],
  foundationCatScore: 3,

  historyInterview: {
    renovationLoad: 0,
    majorRepair: 0,
    pastSettlement: 0,
    neighborDamage: 0,
    fireFloodIncident: 0,
    sensitiveEquipment: { has: false, description: '' },
    usageStatus: 'Đầy đủ 100%',
    continuousOperation247: false,
  },

  floors: [
    {
      id: 'floor_ground',
      floorName: 'Tầng trệt',
      overviewPhotos: [],
      cadSketchPhotoUrl: '',
      cadZonePins: [],
      cadElementPins: [],
      zones: [],
      structuralElements: [],
    },
  ],

  burlandSummary: {
    predominantGrade: 0,
    localMaxGrade: 0,
    governingZoneCode: 'Z-01',
    governingZoneDescription: '',
    representativeness: 'GLOBAL',
    structuralFlagLevel: 'NONE',
    needStructuralEngineerReview: false,
  },

  settlementTilt: {
    diffSettlement: { level: 0, position: '', photoUrl: '', photos: [], notes: '' },
    buildingTilt: { level: 0, xPermille: '', yPermille: '', direction: '', photoUrl: '', photos: [], notes: '' },
    beamSagging: { level: 0, position: '', sagMm: '', description: '', photoUrl: '', notes: '' },
    abnormalCase: { photoUrl: '', photos: [], notes: '' },
    dataSource: ['Quan sát trực quan'],
    reliability: 'HIGH',
    needAdditionalMonitoring: { required: false, notes: '' },
  },

  surveyScope: {
    externalFront: true,
    surveyedFloors: ['Tầng trệt'],
    roofTerrace: false,
    basement: false,
    backyardOuthouse: false,
  },
  accessLimitation: {
    type: 'FULL_100',
    restrictedAreas: [],
    restrictedFloorLevels: [],
    mainReason: '',
    notes: '',
  },
  gisMutationConfirmed: {
    type: 'MATCH',
    notes: '',
  },

  gateDecision: {
    decision: 'ALLOW',
    reason: '',
  },

  ecs: {
    e1: 0,
    e2: 0,
    e3: 0,
    e4: 0,
    e5: 0,
    e6: 0,
    totalEcs: 0,
    ecsClass: 'GOOD',
    engineeringJudgement: { action: 'KEEP', reason: '' },
    isOverrideLocked: false,
  },
  vi: {
    v1: 1,
    v2: 2,
    v3: 2,
    v4: 2,
    v5: 1,
    v6: 1,
    totalVi: 9,
    viAvg: 1.5,
    viClass: 'LOW',
    engineeringJudgement: { action: 'KEEP', reason: '' },
  },

  executiveSummary: {
    keyRisksDefectsText: '',
    specificRecommendationsText: '',
    constructionImpactStatus: 'PENDING',
    braStatus: 'PENDING',
  },

  signatures: {
    ownerFeedback: '',
    preparedBy: {
      fullName: '',
      title: 'Kỹ sư khảo sát hiện trường',
      date: new Date().toISOString().split('T')[0],
      photoUrl: '',
    },
    checkedBy: {
      fullName: '',
      title: 'Quản trị viên khu vực (Zone Admin)',
      date: new Date().toISOString().split('T')[0],
      photoUrl: '',
    },
    ownerRepresentative: {
      fullName: '',
      role: 'Chủ hộ / Đại diện',
      date: new Date().toISOString().split('T')[0],
      photoUrl: '',
    },
    workingMinutesPhotos: [],
  },
});
